<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <AssemblyName>HorusMod</AssemblyName>
    <ProjectDir>/home/critzlez/RiderProjects/Horus-Mod/</ProjectDir>
    <NuclearOptionDir>$(ProjectDir)\NuclearOptionServer_Data\Managed</NuclearOptionDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(NuclearOptionDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(NuclearOptionDir)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Rewired_Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="Mirage">
      <HintPath>$(NuclearOptionDir)\NuclearOption_Data\Managed\Mirage.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
